iteration_parameter_set = {
    "name": "Iteration Parameter Set",
    "notes": "",
    "parameters": [
        {
            "variable_type": "Number of Iterations Type",
            "name": "max_iterations",
            "description": "The maximum number of iterations for the simulation",
            "symbol": None,
            "domain": None,
            "parameter_class": "System",
        },
        {
            "variable_type": "Objective Value Type",
            "name": "tolerance",
            "description": "The tolerance to determine if iteartions can stop",
            "symbol": None,
            "domain": None,
            "parameter_class": "System",
        },
        {
            "variable_type": "Objective Function Type",
            "name": "f",
            "description": "The objective function",
            "symbol": None,
            "domain": None,
            "parameter_class": "Behavioral",
        },
        {
            "variable_type": "Objective Function Derivative Type",
            "name": "f_prime",
            "description": "The objective function derivative",
            "symbol": None,
            "domain": None,
            "parameter_class": "Behavioral",
        },
        {
            "variable_type": "Root Finding Method Type",
            "name": "root_finding_method",
            "description": "The functional parameterization for the root finding method to use",
            "symbol": None,
            "domain": None,
            "parameter_class": "Functional",
        },
    ],
}
